import Cookies from "js-cookies";

const Token = Cookies.getItem("token");

export const config = {
  headers: {
    "Contrent-Type": "multipart/form-data",
    Authorization: `Bearer ${Token}`,
  },
};

export const jobData = [
  {
    img: "https://images.pexels.com/photos/392018/pexels-photo-392018.jpeg",
    title: "Project Manager",
    company: "Dominos Pizza",
    location: "San Francisco, CA, US",
    min_pay: "300000",
    max_pay: "600000",
    level: "Entry level",
    id: "1",
    department: "HR/Org. Development",
  },
  {
    img: "https://images.pexels.com/photos/392018/pexels-photo-392018.jpeg",
    title: "Software Engineer",
    company: "Google",
    location: "New York, NY, US",
    min_pay: "80000",
    max_pay: "150000",
    level: "Mid level",
    id: "2",
    department: "IT/Software Development",
  },
  {
    img: "https://images.pexels.com/photos/392018/pexels-photo-392018.jpeg",
    title: "Marketing Manager",
    company: "Coca-Cola",
    location: "Los Angeles, CA, US",
    min_pay: "50000",
    max_pay: "100000",
    level: "Senior level",
    id: "3",
    department: "Marketing",
  },
  {
    img: "https://images.pexels.com/photos/392018/pexels-photo-392018.jpeg",
    title: "Data Analyst",
    company: "Microsoft",
    location: "Seattle, WA, US",
    min_pay: "60000",
    max_pay: "120000",
    level: "Entry level",
    id: "4",
    department: "Finance",
  },
  {
    img: "https://images.pexels.com/photos/392018/pexels-photo-392018.jpeg",
    title: "Product Manager",
    company: "Amazon",
    location: "San Francisco, CA, US",
    min_pay: "100000",
    max_pay: "200000",
    level: "Mid level",
    id: "5",
    department: "Product Development",
  },
  {
    img: "https://images.pexels.com/photos/392018/pexels-photo-392018.jpeg",
    title: "UX Designer",
    company: "Facebook",
    location: "Menlo Park, CA, US",
    min_pay: "90000",
    max_pay: "180000",
    level: "Senior level",
    id: "6",
    department: "Design",
  },
  {
    img: "https://images.pexels.com/photos/392018/pexels-photo-392018.jpeg",
    title: "Sales Representative",
    company: "Tesla",
    location: "Palo Alto, CA, US",
    min_pay: "40000",
    max_pay: "80000",
    level: "Entry level",
    id: "7",
    department: "Sales",
  },
  {
    img: "https://images.pexels.com/photos/392018/pexels-photo-392018.jpeg",
    title: "Cyber Security Specialist",
    company: "IBM",
    location: "Armonk, NY, US",
    min_pay: "70000",
    max_pay: "140000",
    level: "Mid level",
    id: "8",
    department: "IT/Security",
  },
  {
    img: "https://images.pexels.com/photos/392018/pexels-photo-392018.jpeg",
    title: "HR Generalist",
    company: "Apple",
    location: "Cupertino, CA, US",
    min_pay: "50000",
    max_pay: "100000",
    level: "Entry level",
    id: "9",
    department: "HR",
  },
  {
    img: "https://images.pexels.com/photos/392018/pexels-photo-392018.jpeg",
    title: "Business Development Manager",
    company: "McDonald's",
    location: "Chicago, IL, US",
    min_pay: "60000",
    max_pay: "120000",
    level: "Senior level",
    id: "10",
    department: "Business Development",
  },
  {
    img: "https://images.pexels.com/photos/392018/pexels-photo-392018.jpeg",
    title: "Network Engineer",
    company: "Cisco Systems",
    location: "San Jose, CA, US",
    min_pay: "80000",
    max_pay: "160000",
    level: "Mid level",
    id: "11",
    department: "IT/Networking",
  },
];
